### ISSUE TITLE
и что как

### ISSUE THREAD

**Issue by DrBenvey** [RamilRamil/FigureArea#1]
взяли или сказали что код хуже чем у остальных? (тупо интересно что они считают норм кодом)

**Comment by RamilRamil** [comment]
> взяли или сказали что код хуже чем у остальных? (тупо интересно что они считают норм кодом)

Сказали, что SQL некорректный, не взяли =) про площадь фигуры ничего не сказали

**Comment by DrBenvey** [comment]
принял спс
